version: '3'

services:
  search-service:
    container_name: search-container
    image: dhammanava-search-image
    build:
      context: ./search-esdb-service
    environment:
      CONNECTION_ESDBURL: ${ELASTIC_URL}
      ESDB_USERNAME: ${ELASTIC_USERNAME}
      ESDB_PASSWORD: ${ELASTIC_PASSWORD}
      CORS_TARGET: ${WEB_CORS_TARGET}
    working_dir: /app/search-esdb
    ports:
      - 8081:8081
    depends_on:
      - elastic-db
    networks:
      - backbone

  elastic-db: 
    container_name: elastic-container
    image: dhammanava-elastic-image
    build:
      context: ./elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - 9200:9200
    networks:
      - backbone

  #! Kibana still not working : need to config elastic TSL/SSL cert
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.10.4
  #   ports:
  #     - 5601:5601
  #   environment:
  #     - ELASTICSEARCH_URL=http://elastic-db:9200
  #   depends_on:
  #     - elastic-db
  #   networks:
  #     - backbone

  frontend:
    image: dhammanava-frontend-image
    container_name: frontend-container
    build:
      context: ./frontend
    ports:
      - 5173:8080
    networks:
      - backbone

  auth-db:
    image: postgres:latest
    container_name: auth-postgres-container
    environment:
      POSTGRES_DB: ${AUTH_DB}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./auth-db:/docker-entrypoint-initdb.d
      - ./volumes/database/auth:/var/lib/postgresql/data
    networks:
      - backbone

networks:
  backbone:
    driver: bridge