version: '3'

services:
  search-service:
    image: dhammanava-search-image:latest
    container_name: search-container
    environment:
      CONNECTION_ESDBURL: ${ELASTIC_URL}
      ESDB_USERNAME: ${ELASTIC_USERNAME}
      ESDB_PASSWORD: ${ELASTIC_PASSWORD}
      CORS_TARGET: ${WEB_CORS_TARGET}
    working_dir: /app/search-esdb
    ports:
      - 8081:8081
    depends_on:
      - elastic-db
    networks:
      - backbone

  elastic-db:
    image: dhammanava-elastic-image
    container_name: elastic-container
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - 9200:9200
    networks:
      - backbone

  frontend:
    image: dhammanava-frontend-image:latest
    container_name: frontend-container
    ports:
      - 5173:8080
    networks:
      - backbone

  #! Kibana still not working : need to config elastic TSL/SSL cert
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elastic-db:9200
    depends_on:
      - elastic-db
    networks:
      - backbone
      
  nginx:
    image: dhammanava-nginx-image
    container_name: nginx-container
    ports:
      - 80:80
    networks:
      - backbone
    depends_on:
      - elastic-db
      - search-service
      - frontend
networks:
  backbone:
    driver: bridge