version: '3'

services:
  search-service:
    image: dhammanava-search-image:latest
    container_name: search-container
    environment:
      CONNECTION_ESDBURL: ${ESDB_URL}
      ESDB_USERNAME: ${ESDB_USERNAME}
      ESDB_PASSWORD: ${ESDB_PASSWORD}
      CORS_TARGET: ${WEB_CORS_TARGET}
    working_dir: /app/search-esdb
    ports:
      - 8081:8081
    depends_on:
      - elastic-db
    networks:
      - backbone

  elastic-db:
    image: dhammanava-elastic-image
    container_name: elastic-container
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ESDB_PASSWORD}
    ports:
      - 9200:9200
    networks:
      - backbone

  frontend:
    image: dhammanava-frontend-image:latest
    container_name: frontend-container
    ports:
      - 5173:5173
    environment:
      VITE_SEARCH_API_URL: ${VITE_SEARCH_API_URL}
    networks:
      - backbone

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.10.4
  #   ports:
  #     - 5601:5601
  #   environment:
  #     - ELASTICSEARCH_URL=http://elastic-db:9200
  #   depends_on:
  #     - elastic-db
  #   networks:
  #     - backbone
      
  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - backbone
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot
      - ./certbot/conf/:/etc/letsencrypt

  certbot:
    image: certbot/certbot:latest
    networks:
      - backbone
    volumes:
      - ./certbot/www/:/var/www/certbot
      - ./certbot/conf/:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --force-renewal --email naruemon.npr@gmail.com -d search.dhammanava.net --agree-tos

networks:
  backbone:
    driver: bridge
