{
 "title": "Main Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Search Counter",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "search_counter{job=\"search-analysis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Service Dashboard",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{container=\"auth-container\"} |= ``"
    }
   ]
  },
  {
   "title": "Data service dashboard",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "{container=\"data-container\"} |= ``"
    }
   ]
  },
  {
   "title": "Search Service logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{container=\"search-container\"} |= ``"
    }
   ]
  },
  {
   "title": "Elastic DB Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "{container=\"elastic-container\"} |= ``"
    }
   ]
  }
 ]
}