name: Auth Service CI/CD with Docker 
on:
  workflow_dispatch

jobs:
  build-and-deploy-auth-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Clean Go module cache
        run: go clean -modcache

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with: 
          context: ./auth-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dhammanava-auth-image:latest

      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.LINUX_HOST}}
          username: ${{secrets.LINUX_USERNAME}}
          key: ${{ secrets.LINUX_PRIVATE_KEY }}
          script: |
            docker stop auth-service || true
            docker rm  auth-service || true
            docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/dhammanava-auth-image:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dhammanava-auth-image:latest
            cd dhammanava-search
            docker compose -f docker-compose.prod.yml up -d auth-service
        # Automatically start auth-db service along with auth-service as declare in docker-compose.prod.yml

#TODO : Versioning for docker image
