name : -File- Data source directory
on:
  workflow_dispatch

jobs:
    deploy-data-source-directory: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up SSH
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.LINUX_PRIVATE_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_rsa
                chmod 700 ~/.ssh
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -t rsa ${{ secrets.LINUX_HOST }} >> ~/.ssh/known_hosts
            
            - name: Delete Existing Data Source Directory 
              run: |
                ssh -i ~/.ssh/id_rsa ${{ secrets.LINUX_USERNAME }}@${{ secrets.LINUX_HOST }} "rm -rf ~/dhammanava-search/data"
                
            - name: Copy Data source directory to Server
              run: |
                scp -r -i ~/.ssh/id_rsa data ${{ secrets.LINUX_USERNAME }}@${{ secrets.LINUX_HOST }}:~/dhammanava-search
            