name : -File- Makefile
on:
  workflow_dispatch

jobs:
    deploy-make-file: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up SSH
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.LINUX_PRIVATE_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_rsa
                chmod 700 ~/.ssh
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -t rsa ${{ secrets.LINUX_HOST }} >> ~/.ssh/known_hosts
            
            - name: Delete Existing Makefile 
              run: |
                ssh -i ~/.ssh/id_rsa ${{ secrets.LINUX_USERNAME }}@${{ secrets.LINUX_HOST }} "rm -rf ~/dhammanava-search/Makefile"
                
            - name: Copy Makefile.prod to server and change name to Makefile
              run: |
                scp -i ~/.ssh/id_rsa Makefile.prod ${{ secrets.LINUX_USERNAME }}@${{ secrets.LINUX_HOST }}:~/dhammanava-search/Makefile