name: Nginx CI/CD with Docker 
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-elastic-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with: 
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dhammanava-nginx-image:latest

      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.LINUX_HOST}}
          username: ${{secrets.LINUX_USERNAME}}
          key: ${{ secrets.LINUX_PRIVATE_KEY }}
          script: |
            docker stop nginx || true
            docker rm  nginx || true
            docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/dhammanava-nginx-image:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dhammanava-nginx-image:latest
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d nginx
#TODO : Need to configure cd before run docker-compose (navigate to where store docker-compose file)
#TODO : Versioning for docker image

