name : Setup nginx
on:
  workflow_dispatch

jobs:
  deploy-nginx: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LINUX_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.LINUX_HOST }} >> ~/.ssh/known_hosts

      - name : Delete Existing nginx directory 
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.LINUX_USERNAME }}@${{ secrets.LINUX_HOST }} "rm -rf ~/dhammanava-search/nginx"

      - name: Copy nginx directory to server
        run: |
          scp -r -i ~/.ssh/id_rsa nginx ${{ secrets.LINUX_USERNAME }}@${{ secrets.LINUX_HOST }}:~/dhammanava-search

      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.LINUX_HOST}}
          username: ${{secrets.LINUX_USERNAME}}
          key: ${{ secrets.LINUX_PRIVATE_KEY }}
          script: |
            cd dhammanava-search
            docker stop nginx || true
            docker rm  nginx || true
            docker compose -f docker-compose.prod.yml up --build -d nginx
