name: -Test- Data Management
on: 
  pull_request:
    branches:
      - main
    paths:
      - 'data-management-service/**'
  workflow_dispatch:
jobs:
  test-data-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Download dependencies
        run: cd data-management-service && go mod download && go mod vendor 

      - name: Unit test & integration test
        run: cd data-management-service && go test -v ./...
